jobs:
  metrics:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
      - name: GitHub metrics as SVG image
        uses: lowlighter/metrics@v3.7
        with:
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Europe/Berlin
          plugin_achievements: 'yes'
          plugin_activity: 'yes'
          plugin_followup: 'yes'
          plugin_followup_sections: repositories, user
          plugin_languages: 'yes'
          plugin_languages_details: bytes-size, percentage
          plugin_notable: 'yes'
          plugin_notable_filter: stars:>1000
          plugin_notable_repositories: 'yes'
          plugin_projects: 'yes'
          plugin_projects_descriptions: 'yes'
          token: ${{ secrets.PAT }}
name: Metrics
'on':
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
